"""Add hero_background_image to BlogPost

Revision ID: 2faa66af0e79
Revises: 8c0d3a4ad7dc
Create Date: 2025-05-16 00:11:26.508070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faa66af0e79'
down_revision = '8c0d3a4ad7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_background_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('hero_background_image')

    # ### end Alembic commands ###
