"""Add FlightBookingRequest model

Revision ID: 4472c45c8f55
Revises: 7a7675d1f5e3
Create Date: 2025-05-16 21:36:17.949202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4472c45c8f55'
down_revision = '7a7675d1f5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('departure_city', sa.String(length=100), nullable=False),
    sa.Column('arrival_city', sa.String(length=100), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('trip_type', sa.String(length=20), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('infants', sa.Integer(), nullable=False),
    sa.Column('cabin_class', sa.String(length=50), nullable=False),
    sa.Column('flexible_dates', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_booking_requests')
    # ### end Alembic commands ###
