"""Ensure all User model columns are present

Revision ID: 4bdd4314c1d6
Revises: 85a3abe1269d
Create Date: 2025-05-15 23:02:07.019924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdd4314c1d6'
down_revision = '85a3abe1269d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('profile_image_file', sa.String(length=200), nullable=True))
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('profile_image_file')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
